# Select what we should cache
#cache:
#  paths:
#  - vendor/

.default-mysql: &default-mysql
  # Install required PHP extensions
  - docker-php-ext-install -j$(nproc) mysqli curl
  # set up config files
  - touch backend/config_.php
  - echo "<?php // local config" >> backend/config_.php
  - echo "define('DB_HOST', 'mysql');" >> backend/config_.php
  - echo "define('DB_USER', 'root');" >> backend/config_.php
  - echo "define('DB_PWD', 'mysql');" >> backend/config_.php
  - echo "define('DB_NAME', 'lynxphp');" >> backend/config_.php
  - echo "?>"  >> backend/config_.php
  - cp backend/config_.php backend/config_localhost.php
  - touch frontend/config_.php
  - cp frontend/config_.php frontend/config_localhost.php

.default-pgsql: &default-pgsql
  # Install required PHP extensions
  - docker-php-ext-install -j$(nproc) pgsql curl
  # set up config files
  - touch backend/config_.php
  - echo "<?php // local config" >> backend/config_.php
  - echo "define('DB_HOST', 'pgsql');" >> backend/config_.php
  - echo "define('DB_USER', 'lynxphp');" >> backend/config_.php
  - echo "define('DB_PWD', '');" >> backend/config_.php
  - echo "define('DB_NAME', 'lynxphp');" >> backend/config_.php
  - echo "define('DB_DRIVER', 'pgsql');" >> backend/config_.php
  - echo "?>"  >> backend/config_.php
  - cp backend/config_.php backend/config_localhost.php
  - touch frontend/config_.php
  - cp frontend/config_.php frontend/config_localhost.php

# Why use debian if alpine is faster? Robustness tests?
.debian: &debian
  - apt-get update -yqq
  - apt-get install -yqq git libcurl4-openssl-dev libpq-dev wget curl

.alpine: &alpine
  - apk add curl-dev postgresql-dev

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: "lynxphp"
  MYSQL_ROOT_PASSWORD: "mysql"
  MYSQL_ROOT_HOST: "%"
  POSTGRES_DB: "lynxphp"
  POSTGRES_USER: "lynxphp"
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust

test:nginx:my:atest:
  before_script:
    - *alpine
    - *default-mysql
  image: php:8.0.0-nginx-alpine
  services:
    - name: mysql/mysql-server:latest
      alias: mysql
  tags:
    - docker
  script:
    - tests/run.sh
